import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans, Oswald } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistNoto = Noto_Sans({
  variable: "--font-geist-noto",
  subsets: ["latin"],
})

const geistOswald = Oswald({
  variable: "--font-geist-oswald",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Movies-mh24",
  description: "Generated by Movies-mh24",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistNoto.variable} ${geistOswald.variable} antialiased dark`}
      >
        {children}
      </body>
    </html>
  );
}
